apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- postgres-pvc.yaml
- postgres-deployment.yaml
- postgres-service.yaml
- todo-deployment.yaml
- todo-service.yaml
- todo-route.yaml